{{- if .Values.app.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "advanced-templates.fullname" . }}
  labels:
    {{- include "advanced-templates.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.app.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with (include "advanced-templates.annotations" .) }}
    {{- . | nindent 4 }}
    {{- end }}
spec:
  {{- if .Values.app.ingress.className }}
  ingressClassName: {{ .Values.app.ingress.className }}
  {{- end }}
  {{- if .Values.app.ingress.tls }}
  tls:
  {{- range .Values.app.ingress.tls }}
  - hosts:
    {{- range .hosts }}
    - {{ . | quote }}
    {{- end }}
    secretName: {{ .secretName }}
  {{- end }}
  {{- end }}
  rules:
  {{- include "advanced-templates.ingressHosts" . | nindent 2 }}
{{- end }}
